import uuid
from datetime import datetime, timedelta


def make_mock_threat(
    title: str,
    description: str,
    attack_vector: str,
    severity: str,
    affected_layer: str,
    cve_refs: str,
    source_name: str,
    source_url: str,
    hours_ago: int,
    raw_excerpt: str,
):
    return {
        "id": str(uuid.uuid4()),
        "title": title,
        "description": description,
        "attack_vector": attack_vector,
        "severity": severity,
        "affected_layer": affected_layer,
        "cve_refs": cve_refs,
        "source_name": source_name,
        "source_url": source_url,
        "discovered_at": (datetime.utcnow() - timedelta(hours=hours_ago)).isoformat(),
        "raw_excerpt": raw_excerpt,
    }

# Mock threat data for testing
MOCK_THREATS = [
    make_mock_threat(
        "SQL Injection in Admin Dashboard",
        "A critical SQL injection vulnerability was discovered in the admin dashboard login endpoint. Attackers can bypass authentication and gain unauthorized access to the entire database.",
        "SQL Injection",
        "CRITICAL",
        "Database",
        "CVE-2024-1234",
        "Krebs on Security",
        "https://krebsonsecurity.com",
        2,
        "SQL Injection vulnerability discovered in popular admin framework allowing remote code execution",
    ),
    make_mock_threat(
        "Cross-Site Scripting in Comment Editor",
        "Reflected XSS vulnerability in the comment editor allows attackers to execute arbitrary JavaScript in victim browsers and steal session tokens.",
        "XSS",
        "HIGH",
        "Frontend",
        "CVE-2024-5678",
        "BleepingComputer",
        "https://www.bleepingcomputer.com",
        4,
        "Reflected XSS found in popular publishing platform comment form",
    ),
    make_mock_threat(
        "API Authentication Bypass",
        "API endpoints lack proper authentication validation. Attackers can access protected resources without valid tokens by manipulating request headers.",
        "Auth Bypass",
        "CRITICAL",
        "API",
        "",
        "Schneier on Security",
        "https://www.schneier.com",
        6,
        "REST API authentication mechanism can be bypassed using modified bearer tokens",
    ),
    make_mock_threat(
        "Path Traversal in File Upload",
        "File upload endpoint does not properly sanitize paths, allowing attackers to write files outside the intended upload directory and potentially overwrite critical system files.",
        "Path Traversal",
        "HIGH",
        "API",
        "CVE-2024-9012",
        "CISA Alerts",
        "https://www.cisa.gov",
        8,
        "Directory traversal vulnerability in document management system file upload handler",
    ),
    make_mock_threat(
        "Weak Password Hashing Workflow",
        "Passwords are hashed using MD5 which is cryptographically broken. Attackers can perform dictionary and rainbow table attacks to crack passwords offline.",
        "Cryptographic Weakness",
        "HIGH",
        "Auth",
        "",
        "Rapid7",
        "https://www.rapid7.com",
        10,
        "MD5 password hashing deprecated in modern applications due to collision attacks",
    ),
    make_mock_threat(
        "CSRF Token Validation Missing",
        "POST endpoints lack CSRF token validation, allowing attackers to perform unauthorized actions on behalf of authenticated users.",
        "CSRF",
        "MEDIUM",
        "Frontend",
        "",
        "Google Security Blog",
        "https://security.googleblog.com",
        12,
        "Missing CSRF protection allows unauthorized fund transfers and account modifications",
    ),
    make_mock_threat(
        "Unvalidated Redirect in OAuth Handler",
        "OAuth redirect_uri parameter is not validated, allowing attackers to redirect users to phishing sites and capture authorization codes.",
        "Open Redirect",
        "MEDIUM",
        "Auth",
        "CVE-2024-3456",
        "Cloudflare Security",
        "https://blog.cloudflare.com",
        14,
        "OAuth implementation vulnerable to open redirect attacks via manipulated redirect_uri",
    ),
    make_mock_threat(
        "Insufficient Rate Limiting on Login",
        "Login endpoint lacks rate limiting, enabling brute force attacks. Attackers can attempt unlimited password guesses to compromise user accounts.",
        "Brute Force",
        "MEDIUM",
        "Auth",
        "",
        "Unit 42",
        "https://unit42.paloaltonetworks.com",
        16,
        "No rate limiting on authentication attempts allows rapid brute force login attempts",
    ),
    make_mock_threat(
        "Server-Side Request Forgery in Image Proxy",
        "An image proxy fetches arbitrary URLs without egress restrictions, allowing attackers to reach internal metadata endpoints and internal services.",
        "SSRF",
        "CRITICAL",
        "Backend",
        "CVE-2024-7788",
        "Krebs on Security",
        "https://krebsonsecurity.com",
        18,
        "Image proxy can be abused to query cloud metadata and internal admin panels",
    ),
    make_mock_threat(
        "Command Injection in Diagnostic Endpoint",
        "A diagnostic endpoint passes user-controlled input to a shell command, allowing remote command execution and system compromise.",
        "Command Injection",
        "CRITICAL",
        "Backend",
        "CVE-2024-8122",
        "BleepingComputer",
        "https://www.bleepingcomputer.com",
        20,
        "Diagnostic shell wrapper executes unsanitized host parameter",
    ),
    make_mock_threat(
        "Insecure Deserialization in Session Store",
        "Session tokens are deserialized without integrity checks, enabling attackers to forge objects and trigger code execution paths.",
        "Insecure Deserialization",
        "HIGH",
        "Backend",
        "CVE-2024-8188",
        "Microsoft MSRC",
        "https://msrc.microsoft.com",
        22,
        "Serialized session payload accepted without signature validation",
    ),
    make_mock_threat(
        "Sensitive Data Exposure in Debug Logs",
        "Application logs expose secrets, access tokens, and internal stack traces that can be harvested by an attacker with log access.",
        "Data Exposure",
        "MEDIUM",
        "Observability",
        "",
        "Google Security Blog",
        "https://security.googleblog.com",
        24,
        "Debug logs contain bearer tokens and environment variables",
    ),
    make_mock_threat(
        "JWT Signature Bypass",
        "The API accepts JWTs with a weak or unverified algorithm configuration, allowing attackers to mint arbitrary admin tokens.",
        "Auth Bypass",
        "CRITICAL",
        "Auth",
        "CVE-2024-9001",
        "Cloudflare Security",
        "https://blog.cloudflare.com",
        26,
        "JWT verification skips signature enforcement for legacy tokens",
    ),
    make_mock_threat(
        "Supply Chain Package Swap",
        "A dependency update introduced a malicious package version that can exfiltrate credentials during install or runtime.",
        "Supply Chain",
        "HIGH",
        "Build",
        "",
        "CISA Alerts",
        "https://www.cisa.gov",
        28,
        "Tampered dependency published to registry with credential theft behavior",
    ),
    make_mock_threat(
        "Directory Traversal in Export Feature",
        "Export functionality accepts raw file paths and can be tricked into reading files outside the allowed directory tree.",
        "Path Traversal",
        "HIGH",
        "API",
        "CVE-2024-9017",
        "Unit 42",
        "https://unit42.paloaltonetworks.com",
        30,
        "Export endpoint resolves ../ sequences without normalization",
    ),
    make_mock_threat(
        "Cache Poisoning Through Host Header",
        "The application trusts the Host header when generating cache keys, allowing attackers to poison shared cache entries.",
        "Cache Poisoning",
        "MEDIUM",
        "Edge",
        "",
        "Schneier on Security",
        "https://www.schneier.com",
        32,
        "Host header manipulation changes cache key generation",
    ),
]

def get_mock_threats():
    """Return mock threat data for testing."""
    return MOCK_THREATS

def get_mock_threat_by_id(threat_id: str):
    """Get a single mock threat by ID."""
    for threat in MOCK_THREATS:
        if threat["id"] == threat_id:
            return threat
    return None
