import json
from anthropic import Anthropic
from config import TEST_MODE, ANTHROPIC_API_KEY

client = Anthropic(api_key=ANTHROPIC_API_KEY) if not TEST_MODE else None

SYSTEM_PROMPT = """You are a senior security engineer. You receive structured data about a web application 
attack vector. You must generate TWO things:

1. A Next.js 14 App Router middleware snippet (TypeScript) that detects and blocks 
   this specific attack pattern at the edge. The middleware must:
   - Import from 'next/server'
   - Export a middleware() function
   - Use NextRequest and NextResponse
   - Check request URL, headers, and/or body as appropriate for this attack
   - Return NextResponse.json({error: 'Blocked'}, {status: 403}) on detection
   - Include a comment at the top: // AUTO-GENERATED by Zero-Day Cartographer
   - Be specific to this EXACT attack vector — not a generic security template

2. A POSIX-compatible firewall regex rule (suitable for nginx or ModSecurity) that 
   blocks the same attack pattern.

Respond ONLY with a valid JSON object. No markdown, no backticks. Just JSON.

Format:
{
  "middleware_code": "full TypeScript code as a single string with \\n for newlines",
  "firewall_regex": "the regex pattern string only, no surrounding syntax",
  "explanation": "One sentence: what the code specifically blocks and how"
}
"""

async def run_engineer_agent(threat: dict) -> dict:
    """
    Generate middleware and firewall rules for a specific threat.
    In TEST_MODE, returns realistic sample code.
    """
    if TEST_MODE:
        return get_test_patch_for_threat(threat)
    
    try:
        # Build the user prompt with threat details
        user_prompt = f"""Attack Title: {threat.get('title', 'Unknown')}
Attack Vector: {threat.get('attack_vector', 'Unknown')}
Affected Layer: {threat.get('affected_layer', 'Infrastructure')}
Description: {threat.get('description', '')}
Raw Context: {threat.get('raw_excerpt', '')}
"""
        
        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2000,
            system=SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": user_prompt
                }
            ]
        )
        
        response_text = response.content[0].text
        
        # Parse JSON response
        result = json.loads(response_text)
        
        return {
            "middleware_code": result.get("middleware_code", "// Generation failed."),
            "firewall_regex": result.get("firewall_regex", ""),
            "explanation": result.get("explanation", "No explanation provided.")
        }
    
    except json.JSONDecodeError as e:
        print(f"[ENGINEER ERROR] Failed to parse JSON response: {str(e)}")
        return {
            "middleware_code": "// Generation failed. Please try again.",
            "firewall_regex": "",
            "explanation": "LLM response could not be parsed."
        }
    except Exception as e:
        print(f"[ENGINEER ERROR] {str(e)}")
        return {
            "middleware_code": "// Generation failed. Please try again.",
            "firewall_regex": "",
            "explanation": f"Error: {str(e)}"
        }

def get_test_patch_for_threat(threat: dict) -> dict:
    """Generate test/sample security patches for testing."""
    attack_vector = threat.get("attack_vector", "Unknown").lower()
    
    if "sql" in attack_vector:
        return {
            "middleware_code": """// AUTO-GENERATED by Zero-Day Cartographer
import { NextRequest, NextResponse } from 'next/server';

export function middleware(request: NextRequest) {
  const { searchParams, pathname } = request.nextUrl;
  
  // Detect SQL injection patterns
  const sqlPatterns = [
    /('|(\\-\\-)|(;)|(\\|\\|)|(\\*))/gi,
    /(union|select|insert|update|delete|drop|create|alter)\\s+(from|into|table)/gi,
  ];
  
  const body = request.body?.toString() || '';
  const queryString = searchParams.toString();
  const combinedInput = `${body}${queryString}`;
  
  for (const pattern of sqlPatterns) {
    if (pattern.test(combinedInput)) {
      return NextResponse.json(
        { error: 'Blocked: Potential SQL injection detected' },
        { status: 403 }
      );
    }
  }
  
  return NextResponse.next();
}

export const config = {
  matcher: ['/api/:path*', '/admin/:path*'],
};""",
            "firewall_regex": r"(?i)(union.*select|select.*from|insert.*into|delete.*from|drop.*table|;|--|\\|\\||xp_exec|exec\\s*\\()",
            "explanation": "Detects and blocks common SQL injection patterns in request bodies and query parameters."
        }
    
    elif "xss" in attack_vector:
        return {
            "middleware_code": """// AUTO-GENERATED by Zero-Day Cartographer
import { NextRequest, NextResponse } from 'next/server';

export function middleware(request: NextRequest) {
  const body = request.body?.toString() || '';
  const { searchParams } = request.nextUrl;
  
  // Detect XSS patterns
  const xssPatterns = [
    /<script[^>]*>.*?<\\/script>/gi,
    /javascript:/gi,
    /on\\w+\\s*=/gi,
    /<iframe[^>]*>/gi,
    /<img[^>]*onerror/gi,
  ];
  
  const combinedInput = `${body}${searchParams.toString()}`;
  
  for (const pattern of xssPatterns) {
    if (pattern.test(combinedInput)) {
      return NextResponse.json(
        { error: 'Blocked: Potential XSS payload detected' },
        { status: 403 }
      );
    }
  }
  
  return NextResponse.next();
}

export const config = {
  matcher: ['/api/:path*', '/comments/:path*'],
};""",
            "firewall_regex": r"(?i)(<script|javascript:|on\w+\s*=|<iframe|onerror\s*=|alert\s*\()",
            "explanation": "Blocks requests containing common XSS payload patterns including script tags and event handlers."
        }
    
    elif "path" in attack_vector:
        return {
            "middleware_code": """// AUTO-GENERATED by Zero-Day Cartographer
import { NextRequest, NextResponse } from 'next/server';

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;
  
  // Detect path traversal patterns
  const pathTraversalPatterns = [
    /\\.\\.\\\\/gi,
    /\\.\\.%2f/gi,
    /%2e%2e/gi,
  ];
  
  const decodedPath = decodeURIComponent(pathname);
  
  for (const pattern of pathTraversalPatterns) {
    if (pattern.test(decodedPath)) {
      return NextResponse.json(
        { error: 'Blocked: Path traversal attempt detected' },
        { status: 403 }
      );
    }
  }
  
  return NextResponse.next();
}

export const config = {
  matcher: ['/upload/:path*', '/files/:path*'],
};""",
            "firewall_regex": r"(?i)(\.\.\/|\.\.\\\\|%2e%2e|\.\.%2f|\.\.%5c)",
            "explanation": "Prevents directory traversal attacks by blocking requests with path traversal sequences."
        }
    
    else:
        return {
            "middleware_code": """// AUTO-GENERATED by Zero-Day Cartographer
import { NextRequest, NextResponse } from 'next/server';

export function middleware(request: NextRequest) {
  // Add your custom security logic here based on the threat
  const suspicious = false; // Replace with actual checks
  
  if (suspicious) {
    return NextResponse.json(
      { error: 'Blocked' },
      { status: 403 }
    );
  }
  
  return NextResponse.next();
}

export const config = {
  matcher: ['/api/:path*'],
};""",
            "firewall_regex": r"",
            "explanation": "Generic security middleware template. Customize pattern detection based on specific threat."
        }
